package com.eweb.mapper;

import com.eweb.model.Community_activity;

public interface Community_activityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_activity
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_activity
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int insert(Community_activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_activity
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int insertSelective(Community_activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_activity
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    Community_activity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_activity
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int updateByPrimaryKeySelective(Community_activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_activity
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Community_activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_activity
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int updateByPrimaryKey(Community_activity record);
}