package com.eweb.mapper;

import com.eweb.model.Franchisee;

public interface FranchiseeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table franchisee
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table franchisee
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int insert(Franchisee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table franchisee
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int insertSelective(Franchisee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table franchisee
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    Franchisee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table franchisee
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int updateByPrimaryKeySelective(Franchisee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table franchisee
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int updateByPrimaryKey(Franchisee record);
}