package com.eweb.mapper;

import com.eweb.model.Informtaion;
import com.eweb.model.InformtaionWithBLOBs;

public interface InformtaionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informtaion
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informtaion
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int insert(InformtaionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informtaion
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int insertSelective(InformtaionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informtaion
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    InformtaionWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informtaion
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int updateByPrimaryKeySelective(InformtaionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informtaion
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(InformtaionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table informtaion
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int updateByPrimaryKey(Informtaion record);
}