package com.eweb.mapper;

import com.eweb.model.news;

public interface newsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int insert(news record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int insertSelective(news record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    news selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int updateByPrimaryKeySelective(news record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(news record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int updateByPrimaryKey(news record);
}