package com.eweb.mapper;

import com.eweb.model.ParticipateKey;

public interface ParticipateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participate
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int deleteByPrimaryKey(ParticipateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participate
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int insert(ParticipateKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participate
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    int insertSelective(ParticipateKey record);
}