package com.eweb.model;

import java.util.Date;

public class Community_activity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_activity.id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_activity.title
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_activity.time
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_activity.content
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_activity.id
     *
     * @return the value of community_activity.id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_activity.id
     *
     * @param id the value for community_activity.id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_activity.title
     *
     * @return the value of community_activity.title
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_activity.title
     *
     * @param title the value for community_activity.title
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_activity.time
     *
     * @return the value of community_activity.time
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_activity.time
     *
     * @param time the value for community_activity.time
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_activity.content
     *
     * @return the value of community_activity.content
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_activity.content
     *
     * @param content the value for community_activity.content
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}