package com.eweb.model;

public class Franchisee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column franchisee.id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column franchisee.name
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column franchisee.account
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column franchisee.password
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column franchisee.phone
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column franchisee.address
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column franchisee.id
     *
     * @return the value of franchisee.id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column franchisee.id
     *
     * @param id the value for franchisee.id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column franchisee.name
     *
     * @return the value of franchisee.name
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column franchisee.name
     *
     * @param name the value for franchisee.name
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column franchisee.account
     *
     * @return the value of franchisee.account
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column franchisee.account
     *
     * @param account the value for franchisee.account
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column franchisee.password
     *
     * @return the value of franchisee.password
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column franchisee.password
     *
     * @param password the value for franchisee.password
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column franchisee.phone
     *
     * @return the value of franchisee.phone
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column franchisee.phone
     *
     * @param phone the value for franchisee.phone
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column franchisee.address
     *
     * @return the value of franchisee.address
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column franchisee.address
     *
     * @param address the value for franchisee.address
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}