package com.eweb.model;

public class InformtaionWithBLOBs extends Informtaion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informtaion.content
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informtaion.origin
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private String origin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informtaion.content
     *
     * @return the value of informtaion.content
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informtaion.content
     *
     * @param content the value for informtaion.content
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informtaion.origin
     *
     * @return the value of informtaion.origin
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informtaion.origin
     *
     * @param origin the value for informtaion.origin
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }
}