package com.eweb.model;

public class Informtaion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informtaion.id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informtaion.title
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informtaion.type
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column informtaion.author
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private String author;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informtaion.id
     *
     * @return the value of informtaion.id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informtaion.id
     *
     * @param id the value for informtaion.id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informtaion.title
     *
     * @return the value of informtaion.title
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informtaion.title
     *
     * @param title the value for informtaion.title
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informtaion.type
     *
     * @return the value of informtaion.type
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informtaion.type
     *
     * @param type the value for informtaion.type
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column informtaion.author
     *
     * @return the value of informtaion.author
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column informtaion.author
     *
     * @param author the value for informtaion.author
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }
}