package com.eweb.model;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.u_id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.s_id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private Integer sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.status
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.u_id
     *
     * @return the value of orders.u_id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.u_id
     *
     * @param uId the value for orders.u_id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.s_id
     *
     * @return the value of orders.s_id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.s_id
     *
     * @param sId the value for orders.s_id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.status
     *
     * @return the value of orders.status
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.status
     *
     * @param status the value for orders.status
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}