package com.eweb.model;

public class ParticipateKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participate.u_id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participate.c_id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    private Integer cId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participate.u_id
     *
     * @return the value of participate.u_id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participate.u_id
     *
     * @param uId the value for participate.u_id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participate.c_id
     *
     * @return the value of participate.c_id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participate.c_id
     *
     * @param cId the value for participate.c_id
     *
     * @mbg.generated Wed Aug 08 09:50:05 CST 2018
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }
}